devicemonitor: sighandler::SignalHandler Class Reference
sighandler::SignalHandler Class Reference final
#include <SignalHandler.hpp>
Public Member Functions
SignalHandler (const SignalHandler &)=delete
int isValidSignalNumber (const int signalNumber)
check if signal number is within correct boundaries and it is not unmaskable signals
SignalHandler & operator= (const SignalHandler &)=delete
int popHandler (const int signalNumber)
remove actual siignal handler and restore the previous
int pushHandler (const int signalNumber, const sighandler_t newHandler)
set neẃ signal handler saving the previoius one
int setAllHandlers (const sighandler_t handler=throwSystemErrorException)
set the same handler for all signals
Static Public Member Functions
static SignalHandler & get ()
get singleton instance
Static Public Attributes
static const int MAX_SIG_ID
static const int MIN_SIG_ID
Private Member Functions
SignalHandler ()
Construct a new Signal Handler object.
~SignalHandler ()
Destroy the Signal Handler object.
Private Attributes
std::map< int, std::stack< sighandler_t > > handlers
Detailed Description
Definition at line 14 of file SignalHandler.hpp.
Constructor & Destructor Documentation
SignalHandler() [1/2]
sighandler::SignalHandler::SignalHandler (const SignalHandler &) delete
SignalHandler() [2/2]
sighandler::SignalHandler::SignalHandler () private
Construct a new Signal Handler object.
Definition at line 20 of file SignalHandler.cpp.
References handlers, isValidSignalNumber(), MAX_SIG_ID, and MIN_SIG_ID.
     {
         for (int signalNumber(MIN_SIG_ID); signalNumber < MAX_SIG_ID; ++signalNumber)
         {
             if (isValidSignalNumber(signalNumber) != 0)
             {
                 continue;
             }
             if (handlers.count(signalNumber) == 0)
             {
                 handlers.insert(std::make_pair(signalNumber, std::stack<sighandler_t>()));
             }
         }
     }
~SignalHandler()
sighandler::SignalHandler::~SignalHandler () private
Destroy the Signal Handler object.
Definition at line 37 of file SignalHandler.cpp.
     {
     }
Member Function Documentation
get()
SignalHandler & sighandler::SignalHandler::get (void) static
get singleton instance
Returns
SignalHandler&
Definition at line 42 of file SignalHandler.cpp.
Referenced by initProcedure().
     {
         static SignalHandler instance;
         return instance;
     }
isValidSignalNumber()
int sighandler::SignalHandler::isValidSignalNumber (const int signalNumber)
check if signal number is within correct boundaries and it is not unmaskable signals
Parameters
signalNumber signal id
Returns
int 0 opn success; value < 0 on failure
Definition at line 113 of file SignalHandler.cpp.
References MAX_SIG_ID, and MIN_SIG_ID.
Referenced by popHandler(), pushHandler(), setAllHandlers(), and SignalHandler().
     {
         if ((signalNumber < MIN_SIG_ID) || (signalNumber >= MAX_SIG_ID) || (signalNumber == SIGKILL) || (signalNumber == SIGSTOP))
         {
             return -1;
         }
         return 0;
     }
operator=()
SignalHandler& sighandler::SignalHandler::operator= (const SignalHandler &) delete
popHandler()
int sighandler::SignalHandler::popHandler (const int signalNumber)
remove actual siignal handler and restore the previous
Parameters
signalNumber signalo id
Returns
int 0 on success; value < 0 on failure
Definition at line 68 of file SignalHandler.cpp.
References handlers, and isValidSignalNumber().
     {
         if (isValidSignalNumber(signalNumber) != 0)
         {
             return -1;
         }
         if (handlers[signalNumber].empty())
         {
             return -2;
         }
         sighandler_t actual = signal(signalNumber, handlers[signalNumber].top());
         if (actual == SIG_ERR)
         {
             return -3;
         }
         handlers[signalNumber].pop();
         return 0;
     }
pushHandler()
int sighandler::SignalHandler::pushHandler (const int signalNumber, const sighandler_t newHandler)
set neẃ signal handler saving the previoius one
Parameters
signalNumber signal id
newHandler handler functionpushHandler(signalNumber, handler)
Returns
int 0 on success; value < 0 on failure
Definition at line 49 of file SignalHandler.cpp.
References handlers, and isValidSignalNumber().
Referenced by setAllHandlers().
     {
         if ((isValidSignalNumber(signalNumber) != 0) || (newHandler == nullptr))
         {
             return -1;
         }
         sighandler_t previous = signal(signalNumber, newHandler);
         if (previous == SIG_ERR)
         {
             return -2;
         }
         handlers[signalNumber].push(previous);
         return 0;
     }
setAllHandlers()
int sighandler::SignalHandler::setAllHandlers (const sighandler_t handler = throwSystemErrorException)
set the same handler for all signals
Parameters
handler handler function
Returns
int 0 on success; value < 0 on failure
Definition at line 92 of file SignalHandler.cpp.
References isValidSignalNumber(), MAX_SIG_ID, MIN_SIG_ID, and pushHandler().
     {
         for (int signalNumber(MIN_SIG_ID); signalNumber < MAX_SIG_ID; ++signalNumber)
         {
             if (isValidSignalNumber(signalNumber) != 0)
             {
                 continue;
             }
             int rc(pushHandler(signalNumber, handler));
             if (rc)
             {
                 return rc;
             }
         }
         return 0;
     }
Member Data Documentation
handlers
std::map<int, std::stack<sighandler_t> > sighandler::SignalHandler::handlers private
Definition at line 76 of file SignalHandler.hpp.
Referenced by popHandler(), pushHandler(), and SignalHandler().
MAX_SIG_ID
const int sighandler::SignalHandler::MAX_SIG_ID static
Definition at line 21 of file SignalHandler.hpp.
Referenced by isValidSignalNumber(), setAllHandlers(), and SignalHandler().
MIN_SIG_ID
const int sighandler::SignalHandler::MIN_SIG_ID static
Definition at line 20 of file SignalHandler.hpp.
Referenced by isValidSignalNumber(), setAllHandlers(), and SignalHandler().
The documentation for this class was generated from the following files:
src/libsignalhandler/SignalHandler.hpp
src/libsignalhandler/SignalHandler.cpp