devicemonitor: Application Class Reference
Application Class Reference final
#include <Application.hpp>
Public Member Functions
Application (const Application &)=delete
Application & operator= (const Application &)=delete
int run (void)
void stop (void)
Static Public Member Functions
static Application & get (void)
Private Member Functions
Application ()
Construct a new Application object.
~Application ()
Destroy the Application object.
Private Attributes
AbstractAPI * api = nullptr
MessageProcessor * processor = nullptr
bool runApplication = true
DataStorage storage
Detailed Description
Definition at line 11 of file Application.hpp.
Constructor & Destructor Documentation
Application() [1/2]
Application::Application (const Application &) delete
Application() [2/2]
Application::Application () private
Construct a new Application object.
Definition at line 62 of file Application.cpp.
References api, LOG_FMT_FTL, and processor.
 {
     try
     {
         // TODO: we use only one API in this example; we should use much smarter solution
         api = new RestAPI("./etc/communication_schema/communication_schema_v1.json");
         processor = new MessageProcessor(api);
     }
     catch (const std::exception &e)
     {
         LOG_FMT_FTL("failed to create API; %s", e.what());
         api = nullptr;
     }
 }
~Application()
Application::~Application () private
Destroy the Application object.
Definition at line 78 of file Application.cpp.
References api.
 {
     if (api != nullptr)
     {
         delete api;
         api = nullptr;
     }
 }
Member Function Documentation
get()
Application & Application::get (void) static
Returns
Application&
Definition at line 4 of file Application.cpp.
Referenced by main(), and signalHandler().
 {
     static Application app;
     return app;
 }
operator=()
Application& Application::operator= (const Application &) delete
run()
int Application::run (void)
Definition at line 11 of file Application.cpp.
References api, LOG_MSG_FTL, LOG_MSG_INF, processor, runApplication, MessageProcessor::start(), AbstractAPI::start(), MessageProcessor::stop(), and AbstractAPI::stop().
Referenced by main().
 {
     LOG_MSG_INF("starting application main loop");
     if ((api == nullptr) || (processor == nullptr))
     {
         LOG_MSG_FTL("api and/or processor not initialized; unable to run application");
         return EXIT_FAILURE;
     }
     bool apiStarted(api->start());
     bool processorStarted(false);
     if (apiStarted)
     {
         processorStarted = processor->start();
     }
     if (apiStarted && processorStarted)
     {
         while (runApplication)
         {
             std::this_thread::sleep_for(std::chrono::milliseconds(1000));
         }
     }
     else
     {
         LOG_MSG_FTL("failed to start api and/or message processor");
         return EXIT_FAILURE;
     }
     processor->stop();
     delete processor;
     processor = nullptr;
     api->stop();
     delete api;
     api = nullptr;
     return EXIT_SUCCESS;
 }
stop()
void Application::stop (void)
Definition at line 55 of file Application.cpp.
References LOG_MSG_INF, and runApplication.
Referenced by signalHandler().
 {
     LOG_MSG_INF("stopping main loop");
     runApplication = false;
 }
Member Data Documentation
api
AbstractAPI* Application::api = nullptr private
Definition at line 50 of file Application.hpp.
Referenced by Application(), run(), and ~Application().
processor
MessageProcessor* Application::processor = nullptr private
Definition at line 51 of file Application.hpp.
Referenced by Application(), and run().
runApplication
bool Application::runApplication = true private
Definition at line 53 of file Application.hpp.
Referenced by run(), and stop().
storage
DataStorage Application::storage private
Definition at line 52 of file Application.hpp.
The documentation for this class was generated from the following files:
src/deviceMonitor/Application.hpp
src/deviceMonitor/Application.cpp