devicemonitor: MessageProcessor Class Reference
MessageProcessor Class Reference
#include <MessageProcessor.hpp>
Public Member Functions
MessageProcessor (AbstractAPI *api)
Construct message processor.
bool start (void)
start message processor thread
void stop (void)
stop message processor
Static Public Member Functions
static void notify ()
static method for API to notify message processor that new data are available
Private Member Functions
bool getRunFlag ()
get flag that indicates
void setRunFlag (const bool value)
Set the Run Flag object.
Static Private Member Functions
static void threadBody (MessageProcessor *thisProcessor)
thread body implementation
Private Attributes
AbstractAPI * api
std::thread * processorThread
bool runFlag = false
std::mutex runFlagLock
Static Private Attributes
static std::condition_variable processCondition
static std::mutex processLock
Detailed Description
Definition at line 12 of file MessageProcessor.hpp.
Constructor & Destructor Documentation
MessageProcessor()
MessageProcessor::MessageProcessor (AbstractAPI * api)
Construct message processor.
Parameters
api api from which will message processor read data
Definition at line 8 of file MessageProcessor.cpp.
                                                    : api(api)
 {
 }
Member Function Documentation
getRunFlag()
bool MessageProcessor::getRunFlag () private
get flag that indicates
Returns
true
false
Definition at line 74 of file MessageProcessor.cpp.
References runFlag, and runFlagLock.
Referenced by threadBody().
 {
     std::lock_guard<std::mutex> lock(runFlagLock);
     return runFlag;
 }
notify()
void MessageProcessor::notify () static
static method for API to notify message processor that new data are available
Definition at line 46 of file MessageProcessor.cpp.
References processCondition, and processLock.
Referenced by AbstractAPI::pushNewMessage(), and stop().
 {
     std::unique_lock<std::mutex> lock(processLock);
     processCondition.notify_all();
 }
setRunFlag()
void MessageProcessor::setRunFlag (const bool value) private
Set the Run Flag object.
Parameters
value
Definition at line 81 of file MessageProcessor.cpp.
References runFlag, and runFlagLock.
Referenced by start(), and stop().
 {
     std::lock_guard<std::mutex> lock(runFlagLock);
     runFlag = value;
 }
start()
bool MessageProcessor::start (void)
start message processor thread
Returns
true on success
false on failure
Definition at line 13 of file MessageProcessor.cpp.
References LOG_FMT_FTL, processorThread, setRunFlag(), and threadBody().
Referenced by Application::run().
 {
     try
     {
         setRunFlag(true);
         processorThread = new std::thread(threadBody, this);
     }
     catch (const std::exception &e)
     {
         setRunFlag(false);
         LOG_FMT_FTL("failed to allocate thread memory: %s", e.what());
         return false;
     }
     return true;
 }
stop()
void MessageProcessor::stop (void)
stop message processor
Definition at line 31 of file MessageProcessor.cpp.
References notify(), processorThread, and setRunFlag().
Referenced by Application::run().
 {
     setRunFlag(false);
     notify();
     if (processorThread != nullptr)
     {
         processorThread->join();
         delete processorThread;
         processorThread = nullptr;
     }
 }
threadBody()
void MessageProcessor::threadBody (MessageProcessor * thisProcessor) static private
thread body implementation
Parameters
thisProcessor
Definition at line 53 of file MessageProcessor.cpp.
References DataStorage::addRecord(), api, AbstractAPI::getNextMessage(), getRunFlag(), processCondition, and processLock.
Referenced by start().
 {
     AbstractAPI::pJsonMessage_t message;
     while (thisProcessor->getRunFlag())
     {
         {
             std::unique_lock<std::mutex> lock(processLock);
             message = thisProcessor->api->getNextMessage();
             if (message == nullptr)
             {
                 processCondition.wait(lock);
                 continue;
             }
         }
         DataStorage::addRecord(message);
     }
 }
Member Data Documentation
api
AbstractAPI* MessageProcessor::api private
Definition at line 65 of file MessageProcessor.hpp.
Referenced by threadBody().
processCondition
std::condition_variable MessageProcessor::processCondition static private
Definition at line 68 of file MessageProcessor.hpp.
Referenced by notify(), and threadBody().
processLock
std::mutex MessageProcessor::processLock static private
Definition at line 67 of file MessageProcessor.hpp.
Referenced by notify(), and threadBody().
processorThread
std::thread* MessageProcessor::processorThread private
Definition at line 72 of file MessageProcessor.hpp.
Referenced by start(), and stop().
runFlag
bool MessageProcessor::runFlag = false private
Definition at line 71 of file MessageProcessor.hpp.
Referenced by getRunFlag(), and setRunFlag().
runFlagLock
std::mutex MessageProcessor::runFlagLock private
Definition at line 70 of file MessageProcessor.hpp.
Referenced by getRunFlag(), and setRunFlag().
The documentation for this class was generated from the following files:
src/deviceMonitor/middleware/MessageProcessor.hpp
src/deviceMonitor/middleware/MessageProcessor.cpp