devicemonitor: AbstractAPI Class Reference
AbstractAPI Class Reference abstract
#include <AbstractAPI.hpp>
Public Types
typedef std::shared_ptr< rapidjson::Document > pJsonMessage_t
Public Member Functions
AbstractAPI (const std::string &schema)
Construct a new Abstract API object.
virtual ~AbstractAPI (void)
Destroy the Abstract API object.
pJsonMessage_t getNextMessage (void)
Get the next message in message queue.
bool start (void)
common implementation of API start procedure
void stop (void)
stop API and deallocate resources
Protected Member Functions
bool isValidJSON (rapidjson::Document &document)
checks if json document/message is valid by give JSON schema
bool pushNewMessage (pJsonMessage_t newMessage)
add newly received message to queue
virtual void run (void)=0
derived API will implement its runtime
virtual bool setupApi (void)=0
deviced APIs will implement setup procedures
virtual bool shutdownApi (void)=0
derived APIs will implement shutdown procedures
Private Member Functions
bool getRunFlag ()
safely returns flag if thread should continue to work
void loadJSONSchema (void)
loads json schema for validation on given API
void setRunFlag (const bool value)
safely sets flag if thread should continue to work
Static Private Member Functions
static void threadBody (AbstractAPI *thisApi)
thread body representation - a simple loop with no delay
Private Attributes
std::thread * apiThread
const std::string jsonSchema
std::queue< pJsonMessage_t > messageQueue
std::unique_ptr< rapidjson::SchemaDocument > pSchemaDocument
std::unique_ptr< rapidjson::SchemaValidator > pSchemaValidator
std::mutex queueLock
bool runFlag = false
std::mutex runFlagLock
bool validatorInitialized = false
Detailed Description
Definition at line 19 of file AbstractAPI.hpp.
Member Typedef Documentation
pJsonMessage_t
typedef std::shared_ptr<rapidjson::Document> AbstractAPI::pJsonMessage_t
Definition at line 22 of file AbstractAPI.hpp.
Constructor & Destructor Documentation
AbstractAPI()
AbstractAPI::AbstractAPI (const std::string & schema)
Construct a new Abstract API object.
Parameters
schema json schema for current API
Definition at line 5 of file AbstractAPI.cpp.
References loadJSONSchema().
                                                 : jsonSchema(schema)
 {
     loadJSONSchema();
 }
~AbstractAPI()
AbstractAPI::~AbstractAPI (void) virtual
Destroy the Abstract API object.
Definition at line 11 of file AbstractAPI.cpp.
 {
 }
Member Function Documentation
getNextMessage()
AbstractAPI::pJsonMessage_t AbstractAPI::getNextMessage (void)
Get the next message in message queue.
Returns
pJsonMessage_t or nullptr if queue is empty
Definition at line 61 of file AbstractAPI.cpp.
References messageQueue, and queueLock.
Referenced by MessageProcessor::threadBody().
 {
     std::lock_guard<std::mutex> lock(queueLock);
     if (messageQueue.empty())
     {
         return pJsonMessage_t(nullptr);
     }
     pJsonMessage_t messageToGet(messageQueue.front());
     messageQueue.pop();
     return messageToGet;
 }
getRunFlag()
bool AbstractAPI::getRunFlag () private
safely returns flag if thread should continue to work
Returns
true thread should run
false thread should terminate
Definition at line 141 of file AbstractAPI.cpp.
References runFlag, and runFlagLock.
Referenced by threadBody().
 {
     std::lock_guard<std::mutex> lock(runFlagLock);
     return runFlag;
 }
isValidJSON()
bool AbstractAPI::isValidJSON (rapidjson::Document & document) protected
checks if json document/message is valid by give JSON schema
Parameters
document checked JSON
Returns
true if valid
false if not valid and/or schema is not loaded
Definition at line 76 of file AbstractAPI.cpp.
References LOG_MSG_ERR, pSchemaValidator, and validatorInitialized.
Referenced by RestAPI::postHandler().
 {
     if (!validatorInitialized)
     {
         LOG_MSG_ERR("JSON validator not initialized; unable to check JSON message");
         return false;
     }
     return document.Accept(*pSchemaValidator);
 }
loadJSONSchema()
void AbstractAPI::loadJSONSchema (void) private
loads json schema for validation on given API
Definition at line 103 of file AbstractAPI.cpp.
References jsonSchema, LOG_FMT_FTL, pSchemaDocument, pSchemaValidator, and validatorInitialized.
Referenced by AbstractAPI().
 {
     // prepare input streams
     std::ifstream inputFileStream(jsonSchema);
     rapidjson::IStreamWrapper inputStreamWrapper(inputFileStream);
     // load JSON schema and validate for errors
     rapidjson::Document jsonDocument;
     if (jsonDocument.ParseStream(inputStreamWrapper).HasParseError())
     {
         LOG_FMT_FTL("invalid json schema; error %d; offset: %d", jsonDocument.GetParseError(), jsonDocument.GetErrorOffset());
         return;
     }
     // load schema document
     pSchemaDocument = std::unique_ptr<rapidjson::SchemaDocument>(new rapidjson::SchemaDocument(jsonDocument));
     // load schema validator
     pSchemaValidator = std::unique_ptr<rapidjson::SchemaValidator>(new rapidjson::SchemaValidator(*pSchemaDocument));
     validatorInitialized = true;
 }
 catch (const std::exception &ex)
 {
     LOG_FMT_FTL("unable to load JSON schema", ex.what());
     validatorInitialized = false;
 }
pushNewMessage()
bool AbstractAPI::pushNewMessage (pJsonMessage_t newMessage) protected
add newly received message to queue
Parameters
newMessage newly received message
Returns
true if pushed successfully
false on error
Definition at line 88 of file AbstractAPI.cpp.
References LOG_FMT_ERR, messageQueue, MessageProcessor::notify(), and queueLock.
Referenced by RestAPI::postHandler().
 {
     std::lock_guard<std::mutex> lock(queueLock);
     messageQueue.push(newMessage);
     MessageProcessor::notify();
     return true;
 }
 catch (std::exception &ex)
 {
     LOG_FMT_ERR("unable to push new message to queue; error %s", ex.what());
     return false;
 }
run()
virtual void AbstractAPI::run (void) protected pure virtual
derived API will implement its runtime
Implemented in RestAPI.
Referenced by threadBody().
setRunFlag()
void AbstractAPI::setRunFlag (const bool value) private
safely sets flag if thread should continue to work
Parameters
value flag value
Definition at line 148 of file AbstractAPI.cpp.
References runFlag, and runFlagLock.
Referenced by start(), and stop().
 {
     std::lock_guard<std::mutex> lock(runFlagLock);
     runFlag = value;
 }
setupApi()
virtual bool AbstractAPI::setupApi (void) protected pure virtual
deviced APIs will implement setup procedures
Returns
true on success
false on failure
Implemented in RestAPI.
Referenced by start().
shutdownApi()
virtual bool AbstractAPI::shutdownApi (void) protected pure virtual
derived APIs will implement shutdown procedures
Returns
true
false
Implemented in RestAPI.
Referenced by stop().
start()
bool AbstractAPI::start (void)
common implementation of API start procedure
Returns
true API started successfully
false if API did not start
Definition at line 16 of file AbstractAPI.cpp.
References apiThread, LOG_FMT_FTL, LOG_MSG_ERR, LOG_MSG_FTL, setRunFlag(), setupApi(), threadBody(), and validatorInitialized.
Referenced by Application::run().
 {
     if (!validatorInitialized)
     {
         LOG_MSG_ERR("unable to start API, JSON validator not initialized");
         return false;
     }
     if (!setupApi())
     {
         LOG_MSG_FTL("failed to setup API");
         return false;
     }
     try
     {
         setRunFlag(true);
         apiThread = new std::thread(threadBody, this);
     }
     catch (const std::exception &e)
     {
         setRunFlag(false);
         LOG_FMT_FTL("failed to allocate thread memory: %s", e.what());
         return false;
     }
     return true;
 }
stop()
void AbstractAPI::stop (void)
stop API and deallocate resources
Definition at line 46 of file AbstractAPI.cpp.
References apiThread, setRunFlag(), and shutdownApi().
Referenced by Application::run().
 {
     setRunFlag(false);
     shutdownApi();
     if (apiThread != nullptr)
     {
         apiThread->join();
         delete apiThread;
         apiThread = nullptr;
     }
 }
threadBody()
void AbstractAPI::threadBody (AbstractAPI * thisApi) static private
thread body representation - a simple loop with no delay
Parameters
thisApi
Definition at line 132 of file AbstractAPI.cpp.
References getRunFlag(), and run().
Referenced by start().
 {
     while (thisApi->getRunFlag())
     {
         thisApi->run();
     }
 }
Member Data Documentation
apiThread
std::thread* AbstractAPI::apiThread private
Definition at line 138 of file AbstractAPI.hpp.
Referenced by start(), and stop().
jsonSchema
const std::string AbstractAPI::jsonSchema private
Definition at line 128 of file AbstractAPI.hpp.
Referenced by loadJSONSchema().
messageQueue
std::queue<pJsonMessage_t> AbstractAPI::messageQueue private
Definition at line 134 of file AbstractAPI.hpp.
Referenced by getNextMessage(), and pushNewMessage().
pSchemaDocument
std::unique_ptr<rapidjson::SchemaDocument> AbstractAPI::pSchemaDocument private
Definition at line 130 of file AbstractAPI.hpp.
Referenced by loadJSONSchema().
pSchemaValidator
std::unique_ptr<rapidjson::SchemaValidator> AbstractAPI::pSchemaValidator private
Definition at line 131 of file AbstractAPI.hpp.
Referenced by isValidJSON(), and loadJSONSchema().
queueLock
std::mutex AbstractAPI::queueLock private
Definition at line 133 of file AbstractAPI.hpp.
Referenced by getNextMessage(), and pushNewMessage().
runFlag
bool AbstractAPI::runFlag = false private
Definition at line 137 of file AbstractAPI.hpp.
Referenced by getRunFlag(), and setRunFlag().
runFlagLock
std::mutex AbstractAPI::runFlagLock private
Definition at line 136 of file AbstractAPI.hpp.
Referenced by getRunFlag(), and setRunFlag().
validatorInitialized
bool AbstractAPI::validatorInitialized = false private
Definition at line 129 of file AbstractAPI.hpp.
Referenced by isValidJSON(), loadJSONSchema(), and start().
The documentation for this class was generated from the following files:
src/deviceMonitor/apis/AbstractAPI.hpp
src/deviceMonitor/apis/AbstractAPI.cpp