devicemonitor: device_simulator Namespace Reference
device_simulator Namespace Reference
Classes
class Application
class Device
class Measurements
Functions
def random_boolean ()
Variables
APP
Detailed Description
Main module for device simulator for backend testing
Script will attempt to generate random data for random number of devices for
given amount of time.
1) generate random number of devices with random names (default 1-100 devices)
    ... or ...
   generate specific set of named devices
   1.1) each device can measure from 0 up to 3 values. What values
        the device measures is chosen randomly.
2) during execution
    2.1) randomly decide if device should generate new message with measurements
    2.2) if decided, randomly decide to generate temperature and/or voltage
         and/or current measurements
    NOTE: message may contain 0 - 3 measured values
Function Documentation
random_boolean()
def device_simulator.random_boolean ()
function generates random bool value
Definition at line 31 of file device_simulator.py.
Referenced by device_simulator.Device.__generate_current_measurement(), device_simulator.Device.__generate_temperature_measurement(), device_simulator.Device.__generate_voltage_measurement(), and device_simulator.Device.generate_message().
 def random_boolean():
     """
     function generates random bool value
     """
     return random.randint(0, 1) == 0
Variable Documentation
APP
device_simulator.APP
Initial value:
 =  Application(
     device_names=["device-1", "device-2", "device-3", "device-4"])
Definition at line 302 of file device_simulator.py.