devicemonitor: src/liblogger/Logger.hpp File Reference
Logger.hpp File Reference
#include <stdio.h>
Macros
#define LOG_EXIT_FAILURE -1
#define LOG_EXIT_SUCCESS 0
#define LOG_FMT_DBG(_MSG_, ...) logWriteMessage_f(logDbg_e, __LINE__, __FILE__, __func__, _MSG_, ##__VA_ARGS__)
#define LOG_FMT_DEV(_MSG_, ...) logWriteMessage_f(logDev_e, __LINE__, __FILE__, __func__, _MSG_, ##__VA_ARGS__)
#define LOG_FMT_ERR(_MSG_, ...) logWriteMessage_f(logErr_e, __LINE__, __FILE__, __func__, _MSG_, ##__VA_ARGS__)
#define LOG_FMT_FTL(_MSG_, ...) logWriteMessage_f(logFtl_e, __LINE__, __FILE__, __func__, _MSG_, ##__VA_ARGS__)
#define LOG_FMT_INF(_MSG_, ...) logWriteMessage_f(logInf_e, __LINE__, __FILE__, __func__, _MSG_, ##__VA_ARGS__)
#define LOG_FMT_WRN(_MSG_, ...) logWriteMessage_f(logWrn_e, __LINE__, __FILE__, __func__, _MSG_, ##__VA_ARGS__)
#define LOG_MESSAGE_BUFFER_SIZE 1024
#define LOG_MSG_DBG(_MSG_) logWriteMessage_f(logDbg_e, __LINE__, __FILE__, __func__, _MSG_)
#define LOG_MSG_DEV(_MSG_) logWriteMessage_f(logDev_e, __LINE__, __FILE__, __func__, _MSG_)
#define LOG_MSG_ERR(_MSG_) logWriteMessage_f(logErr_e, __LINE__, __FILE__, __func__, _MSG_)
#define LOG_MSG_FTL(_MSG_) logWriteMessage_f(logFtl_e, __LINE__, __FILE__, __func__, _MSG_)
#define LOG_MSG_INF(_MSG_) logWriteMessage_f(logInf_e, __LINE__, __FILE__, __func__, _MSG_)
#define LOG_MSG_WRN(_MSG_) logWriteMessage_f(logWrn_e, __LINE__, __FILE__, __func__, _MSG_)
Enumerations
enum logSeverityLevel_t {
logDev_e = 0, logDbg_e, logInf_e, logWrn_e,
logErr_e, logFtl_e
}
Functions
int logDestroy_f (void)
function de-initializes logger (writes all remaining message to stream a release resources)
int logInitialize_f (FILE *stream, const logSeverityLevel_t level)
initialize logger for usage
int logLockLoggerStream ()
lock logger stream to perform other operations
int logSetLevel_f (const logSeverityLevel_t level)
set log level during runtime
int logUnlockLoggerStream ()
unlock logger stream to resume normal loggin operations
int logWriteMessage_f (const logSeverityLevel_t severity, const int line, const char *file, const char *function, const char *format,...)
write message to log stream
Macro Definition Documentation
LOG_EXIT_FAILURE
#define LOG_EXIT_FAILURE -1
Definition at line 15 of file Logger.hpp.
Referenced by logDestroy_f(), logInitialize_f(), logSetLevel_f(), and logWriteMessage_f().
LOG_EXIT_SUCCESS
#define LOG_EXIT_SUCCESS 0
Definition at line 16 of file Logger.hpp.
Referenced by logDestroy_f(), logInitialize_f(), logSetLevel_f(), and logWriteMessage_f().
LOG_FMT_DBG
#define LOG_FMT_DBG (_MSG_, ...) logWriteMessage_f(logDbg_e, __LINE__, __FILE__, __func__, _MSG_, ##__VA_ARGS__)
Definition at line 110 of file Logger.hpp.
Referenced by RestAPI::postHandler().
LOG_FMT_DEV
#define LOG_FMT_DEV (_MSG_, ...) logWriteMessage_f(logDev_e, __LINE__, __FILE__, __func__, _MSG_, ##__VA_ARGS__)
Definition at line 109 of file Logger.hpp.
LOG_FMT_ERR
#define LOG_FMT_ERR (_MSG_, ...) logWriteMessage_f(logErr_e, __LINE__, __FILE__, __func__, _MSG_, ##__VA_ARGS__)
Definition at line 113 of file Logger.hpp.
Referenced by DataStorage::addRecord(), RestAPI::postHandler(), AbstractAPI::pushNewMessage(), RestAPI::run(), RestAPI::setupApi(), and RestAPI::shutdownApi().
LOG_FMT_FTL
#define LOG_FMT_FTL (_MSG_, ...) logWriteMessage_f(logFtl_e, __LINE__, __FILE__, __func__, _MSG_, ##__VA_ARGS__)
Definition at line 114 of file Logger.hpp.
Referenced by Application::Application(), AbstractAPI::loadJSONSchema(), MessageProcessor::start(), and AbstractAPI::start().
LOG_FMT_INF
#define LOG_FMT_INF (_MSG_, ...) logWriteMessage_f(logInf_e, __LINE__, __FILE__, __func__, _MSG_, ##__VA_ARGS__)
Definition at line 111 of file Logger.hpp.
Referenced by signalHandler().
LOG_FMT_WRN
#define LOG_FMT_WRN (_MSG_, ...) logWriteMessage_f(logWrn_e, __LINE__, __FILE__, __func__, _MSG_, ##__VA_ARGS__)
Definition at line 112 of file Logger.hpp.
LOG_MESSAGE_BUFFER_SIZE
#define LOG_MESSAGE_BUFFER_SIZE 1024
Definition at line 17 of file Logger.hpp.
Referenced by logWriteMessage_f().
LOG_MSG_DBG
#define LOG_MSG_DBG (_MSG_) logWriteMessage_f(logDbg_e, __LINE__, __FILE__, __func__, _MSG_)
Definition at line 103 of file Logger.hpp.
LOG_MSG_DEV
#define LOG_MSG_DEV (_MSG_) logWriteMessage_f(logDev_e, __LINE__, __FILE__, __func__, _MSG_)
Definition at line 102 of file Logger.hpp.
LOG_MSG_ERR
#define LOG_MSG_ERR (_MSG_) logWriteMessage_f(logErr_e, __LINE__, __FILE__, __func__, _MSG_)
Definition at line 106 of file Logger.hpp.
Referenced by AbstractAPI::isValidJSON(), and AbstractAPI::start().
LOG_MSG_FTL
#define LOG_MSG_FTL (_MSG_) logWriteMessage_f(logFtl_e, __LINE__, __FILE__, __func__, _MSG_)
Definition at line 107 of file Logger.hpp.
Referenced by initProcedure(), Application::run(), and AbstractAPI::start().
LOG_MSG_INF
#define LOG_MSG_INF (_MSG_) logWriteMessage_f(logInf_e, __LINE__, __FILE__, __func__, _MSG_)
Definition at line 104 of file Logger.hpp.
Referenced by Application::run(), and Application::stop().
LOG_MSG_WRN
#define LOG_MSG_WRN (_MSG_) logWriteMessage_f(logWrn_e, __LINE__, __FILE__, __func__, _MSG_)
Definition at line 105 of file Logger.hpp.
Enumeration Type Documentation
logSeverityLevel_t
enum logSeverityLevel_t
Enumerator
logDev_e
logDbg_e
logInf_e
logWrn_e
logErr_e
logFtl_e
Definition at line 19 of file Logger.hpp.
     {
         logDev_e = 0,
         logDbg_e,
         logInf_e,
         logWrn_e,
         logErr_e,
         logFtl_e,
     } logSeverityLevel_t;
Function Documentation
logDestroy_f()
int logDestroy_f (void)
function de-initializes logger (writes all remaining message to stream a release resources)
Returns
int returns LOG_EXIT_SUCCESS on success; LOG_EXIT_FAILURE on failure
Definition at line 477 of file Logger.cpp.
References False_e, logData_t::first, logData_t::isInitialized, logData_t::last, lockLoggerData(), LOG_EXIT_FAILURE, LOG_EXIT_SUCCESS, logData_t::logCondition, logData_t::logThread, logMessage::next, logData_t::queueLength, logData_t::queueLock, logData_t::runLogThread, logData_t::stream, unlockLoggerData(), and writeMessage().
Referenced by exitProcedure().
     {
         /* lock logger data */
         if (lockLoggerData() != 0)
         {
             return LOG_EXIT_FAILURE;
         }
         /* logger was never initialzed; unlock mutex and exit */
         if (loggerData.isInitialized == False_e)
         {
             unlockLoggerData();
             return LOG_EXIT_FAILURE;
         }
         /* set log processing flag to false */
         loggerData.runLogThread = False_e;
         /* lock logger data */
         unlockLoggerData();
         int rc = LOG_EXIT_SUCCESS;
         /* signal the thread in case it is waiting on send condition */
         if (pthread_cond_signal(&loggerData.logCondition) != 0)
         {
             perror("failed to send condition signal on exit");
             rc = LOG_EXIT_FAILURE;
         }
         /* wait for thread to finish */
         if (pthread_join(loggerData.logThread,  NULL) != 0)
         {
             perror("logger thread failed to join");
             rc = LOG_EXIT_FAILURE;
         }
         /* release condition variable */
         if (pthread_cond_destroy(&loggerData.logCondition) != 0)
         {
             perror("failed to destroy log condition");
             rc = LOG_EXIT_FAILURE;
         }
         /* release queue mutex */
         if (pthread_mutex_destroy(&loggerData.queueLock) != 0)
         {
             perror("failed to destroy queue mutex");
             rc = LOG_EXIT_FAILURE;
         }
         /* write all remaining messages in queue */
         while (loggerData.first != NULL)
         {
             logMessage_t* toDelete = loggerData.first;
             writeMessage(loggerData.stream, toDelete);
             loggerData.first = loggerData.first->next;
             free(toDelete);
         }
         loggerData.first = NULL;
         loggerData.last = NULL;
         loggerData.queueLength = 0;
         /* flush stream */
         if (fflush(loggerData.stream) != 0)
         {
             perror("failed  to flush log stream");
             rc = LOG_EXIT_FAILURE;
         }
         /* close stream */
         if (fclose(loggerData.stream) != 0)
         {
             perror("failed to close log stream");
             rc = LOG_EXIT_FAILURE;
         }
         loggerData.isInitialized = False_e;
         /* unlock logger data */
         if (unlockLoggerData() != 0)
         {
             rc = LOG_EXIT_FAILURE;
         }
         return rc;
     }
logInitialize_f()
int logInitialize_f (FILE * stream, const logSeverityLevel_t level)
initialize logger for usage
Parameters
stream file stream to write messages; if NULL is passed, stdout is used
level log level; messages with lower level than specified will not be written
Returns
int returns LOG_EXIT_SUCCESS on success; LOG_EXIT_FAILURE value on failure
Definition at line 567 of file Logger.cpp.
References False_e, logData_t::first, logData_t::isInitialized, logData_t::last, logData_t::level, lockLoggerData(), LOG_EXIT_FAILURE, LOG_EXIT_SUCCESS, logData_t::logCondition, loggerThreadBody(), logData_t::logThread, logData_t::queueLength, logData_t::queueLock, logData_t::runLogThread, logData_t::stream, True_e, and unlockLoggerData().
Referenced by initProcedure().
     {
         /* lock logger data */
         if (lockLoggerData() != 0)
         {
             return LOG_EXIT_FAILURE;
         }
         /* do not initialize  twice or more */
         if (loggerData.isInitialized == True_e)
         {
             perror("WRN logger already initialized (log-init)");
             unlockLoggerData();
             return LOG_EXIT_FAILURE;
         }
         /* output stream */
         if (stream == NULL)
         {
             loggerData.stream = stdout;
         }
         else
         {
             loggerData.stream = stream;
         }
         /* logging level */
         loggerData.level = level;
         /* actual queue length */
         loggerData.queueLength = 0;
         /* first message in log queue */
         loggerData.first = NULL;
         /* last message in  log queue */
         loggerData.last = NULL;
         /* message queue lock */
         if (pthread_mutex_init(&loggerData.queueLock, NULL) != 0)
         {
             perror("FTL unable to create queue lock");
             fclose(loggerData.stream);
             unlockLoggerData();
             return LOG_EXIT_FAILURE;
         }
         /* log write condition variable */
         if (pthread_cond_init(&loggerData.logCondition, NULL))
         {
             perror("FTL unable to create queue condition");
             fclose(loggerData.stream);
             pthread_mutex_destroy(&loggerData.queueLock);
             unlockLoggerData();
             return LOG_EXIT_FAILURE;
         }
         /*flag that indicates that logger thread should run */
         loggerData.runLogThread = True_e;
         /* logger thread identifier */
         if (pthread_create(&loggerData.logThread, NULL, loggerThreadBody, NULL) != 0)
         {
             perror("FTL unable to create logger thread");
             fclose(loggerData.stream);
             pthread_mutex_destroy(&loggerData.queueLock);
             pthread_cond_destroy(&loggerData.logCondition);
             return LOG_EXIT_FAILURE;
         }
         /* flag if logger is initialized */
         loggerData.isInitialized = True_e;
         /* finally unlock logger data */
         if (unlockLoggerData() != 0)
         {
             /* this is very bad situation right here; destroy all we can and try again to unlock */
             loggerData.runLogThread = False_e;
             loggerData.isInitialized = False_e;
             fclose(loggerData.stream);
             pthread_mutex_destroy(&loggerData.queueLock);
             pthread_cond_destroy(&loggerData.logCondition);
             unlockLoggerData();
             return LOG_EXIT_FAILURE;
         }
         return LOG_EXIT_SUCCESS;
     }
logLockLoggerStream()
int logLockLoggerStream ()
lock logger stream to perform other operations
Returns
int returns LOG_EXIT_SUCCESS on success; LOG_EXIT_FAILURE value on failure
Definition at line 656 of file Logger.cpp.
References lockStream().
     {
         return lockStream();
     }
logSetLevel_f()
int logSetLevel_f (const logSeverityLevel_t level)
set log level during runtime
Parameters
level new logging level
Returns
int return LOG_EXIT_SUCCESS on success; LOG_EXIT_FAILURE value on failure
Definition at line 169 of file Logger.cpp.
References logData_t::level, lockLoggerData(), LOG_EXIT_FAILURE, LOG_EXIT_SUCCESS, and unlockLoggerData().
     {
         if (lockLoggerData() != 0)
         {
             return LOG_EXIT_FAILURE;
         }
         loggerData.level = level;
         if (unlockLoggerData() != 0)
         {
             return LOG_EXIT_FAILURE;
         }
         return LOG_EXIT_SUCCESS;
     }
logUnlockLoggerStream()
int logUnlockLoggerStream ()
unlock logger stream to resume normal loggin operations
Returns
int returns LOG_EXIT_SUCCESS on success; LOG_EXIT_FAILURE value on failure
Definition at line 661 of file Logger.cpp.
References unlockStream().
     {
         return unlockStream();
     }
logWriteMessage_f()
int logWriteMessage_f (const logSeverityLevel_t severity, const int line, const char * file, const char * function, const char * format, ...)
write message to log stream
Parameters
severity message severity
line line where message originated
file file where message originated
function function where message originated
format message/format to write
... optional arguments for format
Returns
int returns LOG_EXIT_SUCCESS on success; LOG_EXIT_FAILURE value on failure
Definition at line 233 of file Logger.cpp.
References logMessage::buffer, False_e, logMessage::file, logData_t::first, logMessage::function, logData_t::isInitialized, logData_t::last, logData_t::level, logMessage::line, lockLoggerData(), lockLoggerQueue(), LOG_EXIT_FAILURE, LOG_EXIT_SUCCESS, LOG_MESSAGE_BUFFER_SIZE, logData_t::logCondition, logMessage::next, logData_t::queueLength, logMessage::severity, logMessage::threadId, logMessage::time, unlockLoggerData(), and unlockLoggerQueue().
     {
         /* lock logger data */
         if (lockLoggerData() != 0)
         {
             return LOG_EXIT_FAILURE;
         }
         /* check if logger is initialized */
         if (loggerData.isInitialized == False_e)
         {
             unlockLoggerData();
             return LOG_EXIT_FAILURE;
         }
         /* filter out messages under specified level */
         if (severity < loggerData.level)
         {
             unlockLoggerData();
             return LOG_EXIT_SUCCESS;
         }
         /* unlock logger data*/
         if (unlockLoggerData() != 0)
         {
             return LOG_EXIT_FAILURE;
         }
         /* allocate memory for new message */
         logMessage_t* newMessage = (logMessage_t*) calloc(1, sizeof(logMessage_t));
         if (newMessage == NULL)
         {
             perror("FTL unable to allocate log message");
             return LOG_EXIT_FAILURE;
         }
         /* set message data */
         newMessage->file = file;
         newMessage->function = function;
         newMessage->line = line;
         newMessage->severity = severity;
         newMessage->threadId = syscall(SYS_gettid);
         newMessage->time = time(NULL);
         va_list args;
         va_start(args,  format);
         vsnprintf(newMessage->buffer, LOG_MESSAGE_BUFFER_SIZE, format, args);
         va_end(args);
         /* lock message queue */
         if (lockLoggerQueue() != 0)
         {
             free(newMessage);
             return LOG_EXIT_FAILURE;
         }
         /* if queue is empty */
         if (loggerData.queueLength == 0)
         {
             loggerData.first = newMessage;
             loggerData.last = newMessage;
         }
         else /* queue not empty  */
         {
             loggerData.last->next = newMessage;
             loggerData.last = newMessage;
         }
         loggerData.queueLength++;
         int rc = LOG_EXIT_SUCCESS;
         /* send signal to thread that new message is  present */
         if (pthread_cond_signal(&loggerData.logCondition) != 0)
         {
             perror("FTL unable to send condition signal to logger thread");
             rc = LOG_EXIT_FAILURE;
         }
         /* unlock message queue */
         if (unlockLoggerQueue() != 0)
         {
             rc = LOG_EXIT_FAILURE;
         }
         return rc;
     }