devicemonitor: src/deviceMonitor/main.cpp File Reference
main.cpp File Reference
#include "Logger.hpp"
#include "apis/RestAPI.hpp"
#include "SignalHandler.hpp"
#include "Application.hpp"
#include <cstdlib>
#include <iostream>
Functions
void exitProcedure (void)
int initProcedure (void)
int main (void)
void signalHandler (const int signum)
Function Documentation
exitProcedure()
void exitProcedure (void)
Definition at line 23 of file main.cpp.
References logDestroy_f().
Referenced by main().
 {
     logger::logDestroy_f();
 }
initProcedure()
int initProcedure (void)
Returns
int
Definition at line 33 of file main.cpp.
References sighandler::SignalHandler::get(), LOG_MSG_FTL, logDbg_e, logInitialize_f(), and signalHandler().
Referenced by main().
 {
     logger::logInitialize_f(nullptr, logger::logDbg_e);
     if (sighandler::SignalHandler::get().setAllHandlers(signalHandler) != 0)
     {
         LOG_MSG_FTL("unable to register application termination handler");
         return EXIT_FAILURE;
     }
     if (sighandler::SignalHandler::get().pushHandler(SIGWINCH, SIG_IGN) != 0)
     {
         LOG_MSG_FTL("unable to set action for Window change signal");
         return EXIT_FAILURE;
     }
     return EXIT_SUCCESS;
 }
main()
int main (void)
Definition at line 52 of file main.cpp.
References exitProcedure(), Application::get(), initProcedure(), and Application::run().
 {
     if (atexit(exitProcedure) != 0)
     {
         std::cerr << "failed to register exit procedure" << std::endl;
         return EXIT_FAILURE;
     }
     if (initProcedure() != EXIT_SUCCESS)
     {
         return EXIT_FAILURE;
     }
     return Application::get().run();
 }
 catch (const std::exception &e)
 {
     std::cerr << "unexpected exception: " << e.what() << std::endl;
     return EXIT_FAILURE;
 }
signalHandler()
void signalHandler (const int signum)
Parameters
signum
Definition at line 13 of file main.cpp.
References Application::get(), LOG_FMT_INF, and Application::stop().
Referenced by initProcedure().
 {
     LOG_FMT_INF("received termination signal %d", signum);
     Application::get().stop();
 }