devicemonitor: RestAPI Class Reference
RestAPI Class Reference
#include <RestAPI.hpp>
Public Types
typedef std::shared_ptr< rapidjson::Document > pJsonMessage_t
Public Member Functions
RestAPI (const std::string &schema, const uint16_t port=50000)
Construct a new Rest API object.
virtual ~RestAPI ()
Destroy the Rest API object.
pJsonMessage_t getNextMessage (void)
Get the next message in message queue.
bool start (void)
common implementation of API start procedure
void stop (void)
stop API and deallocate resources
Protected Member Functions
bool isValidJSON (rapidjson::Document &document)
checks if json document/message is valid by give JSON schema
bool pushNewMessage (pJsonMessage_t newMessage)
add newly received message to queue
virtual void run () override
perform API runtime
virtual bool setupApi () override
perform API setup
virtual bool shutdownApi () override
perform API teardown
Static Protected Member Functions
static void getHandler (const std::shared_ptr< restbed::Session > session)
Get the Handler object.
static void postHandler (const std::shared_ptr< restbed::Session > session)
HTTP POST method handler.
Private Attributes
const uint16_t port
std::shared_ptr< restbed::Resource > resourceGet
std::shared_ptr< restbed::Resource > resourcePost
restbed::Service service
std::shared_ptr< restbed::Settings > settings
Static Private Attributes
static RestAPI * thisApi
Detailed Description
Definition at line 10 of file RestAPI.hpp.
Member Typedef Documentation
pJsonMessage_t
typedef std::shared_ptr<rapidjson::Document> AbstractAPI::pJsonMessage_t inherited
Definition at line 22 of file AbstractAPI.hpp.
Constructor & Destructor Documentation
RestAPI()
RestAPI::RestAPI (const std::string & schema, const uint16_t port = 50000)
Construct a new Rest API object.
Parameters
schema JSON validation schema
port
Definition at line 7 of file RestAPI.cpp.
References thisApi.
                                                              : AbstractAPI(schema),
                                                                    port(port),
                                                                    settings(std::make_shared<restbed::Settings>()),
                                                                    resourcePost(std::make_shared<restbed::Resource>()),
                                                                    resourceGet(std::make_shared<restbed::Resource>())
 {
     thisApi = this;
 }
~RestAPI()
RestAPI::~RestAPI () virtual
Destroy the Rest API object.
Definition at line 66 of file RestAPI.cpp.
 {
 }
Member Function Documentation
getHandler()
void RestAPI::getHandler (const std::shared_ptr< restbed::Session > session) static protected
Get the Handler object.
Parameters
session
Definition at line 110 of file RestAPI.cpp.
References DataStorage::getResults().
Referenced by setupApi().
 {
     const std::string &results(DataStorage::getResults());
     session->close(restbed::OK, results);
 }
getNextMessage()
AbstractAPI::pJsonMessage_t AbstractAPI::getNextMessage (void) inherited
Get the next message in message queue.
Returns
pJsonMessage_t or nullptr if queue is empty
Definition at line 61 of file AbstractAPI.cpp.
References AbstractAPI::messageQueue, and AbstractAPI::queueLock.
Referenced by MessageProcessor::threadBody().
 {
     std::lock_guard<std::mutex> lock(queueLock);
     if (messageQueue.empty())
     {
         return pJsonMessage_t(nullptr);
     }
     pJsonMessage_t messageToGet(messageQueue.front());
     messageQueue.pop();
     return messageToGet;
 }
isValidJSON()
bool AbstractAPI::isValidJSON (rapidjson::Document & document) protected inherited
checks if json document/message is valid by give JSON schema
Parameters
document checked JSON
Returns
true if valid
false if not valid and/or schema is not loaded
Definition at line 76 of file AbstractAPI.cpp.
References LOG_MSG_ERR, AbstractAPI::pSchemaValidator, and AbstractAPI::validatorInitialized.
Referenced by postHandler().
 {
     if (!validatorInitialized)
     {
         LOG_MSG_ERR("JSON validator not initialized; unable to check JSON message");
         return false;
     }
     return document.Accept(*pSchemaValidator);
 }
postHandler()
void RestAPI::postHandler (const std::shared_ptr< restbed::Session > session) static protected
HTTP POST method handler.
Parameters
session
Definition at line 71 of file RestAPI.cpp.
References AbstractAPI::isValidJSON(), LOG_FMT_DBG, LOG_FMT_ERR, AbstractAPI::pushNewMessage(), and thisApi.
Referenced by setupApi().
 {
     const auto request = session->get_request();
     size_t contentLength;
     request->get_header("Content-Length", contentLength);
     LOG_FMT_DBG("received %u bytes @ POST %s", contentLength, request->get_path().c_str());
     session->fetch(contentLength, [](const std::shared_ptr<restbed::Session> session, const restbed::Bytes &body)
                    {
                        const std::string buffer((char *)body.data(), body.size());
                        pJsonMessage_t inMessage(std::make_shared<rapidjson::Document>());
                        if (inMessage->Parse(buffer.c_str()).HasParseError())
{
                            session->close(restbed::BAD_REQUEST);
                            LOG_FMT_ERR("invalid JSON format; offset: %d; message: %s", inMessage->GetErrorOffset(), buffer.c_str());
                            return;
                        }
                        if (!thisApi->isValidJSON(*inMessage))
{
                            session->close(restbed::BAD_REQUEST);
                            LOG_FMT_ERR("invalid JSON message; %s", buffer.c_str());
                            return;
                        }
                        if (!thisApi->pushNewMessage(inMessage))
{
                            session->close(restbed::INTERNAL_SERVER_ERROR);
                            return;
                        }
                        session->close(restbed::OK);
                    });
 }
pushNewMessage()
bool AbstractAPI::pushNewMessage (pJsonMessage_t newMessage) protected inherited
add newly received message to queue
Parameters
newMessage newly received message
Returns
true if pushed successfully
false on error
Definition at line 88 of file AbstractAPI.cpp.
References LOG_FMT_ERR, AbstractAPI::messageQueue, MessageProcessor::notify(), and AbstractAPI::queueLock.
Referenced by postHandler().
 {
     std::lock_guard<std::mutex> lock(queueLock);
     messageQueue.push(newMessage);
     MessageProcessor::notify();
     return true;
 }
 catch (std::exception &ex)
 {
     LOG_FMT_ERR("unable to push new message to queue; error %s", ex.what());
     return false;
 }
run()
void RestAPI::run (void) override protected virtual
perform API runtime
Implements AbstractAPI.
Definition at line 42 of file RestAPI.cpp.
References LOG_FMT_ERR, service, and settings.
 {
     service.start(settings);
 }
 catch (const std::exception &e)
 {
     LOG_FMT_ERR("API runtime exception: %s", e.what());
 }
setupApi()
bool RestAPI::setupApi (void) override protected virtual
perform API setup
Returns
true on success
false on failure
Implements AbstractAPI.
Definition at line 17 of file RestAPI.cpp.
References getHandler(), LOG_FMT_ERR, port, postHandler(), resourceGet, resourcePost, service, and settings.
 {
     settings->set_port(port);
     settings->set_default_header("Connection", "close");
     // FIXME: only for demonstration purposes; need update
     resourcePost->set_path("/device/measurement");
     resourcePost->set_method_handler("POST", postHandler);
     resourceGet->set_path("/device/results");
     resourceGet->set_method_handler("GET", getHandler);
     service.publish(resourcePost);
     service.publish(resourceGet);
     return true;
 }
 catch (const std::exception &e)
 {
     LOG_FMT_ERR("API setup exception: %s", e.what());
     return false;
 }
shutdownApi()
bool RestAPI::shutdownApi (void) override protected virtual
perform API teardown
Returns
true on success
false on failure
Implements AbstractAPI.
Definition at line 53 of file RestAPI.cpp.
References LOG_FMT_ERR, and service.
 {
     service.stop();
     return true;
 }
 catch (const std::exception &e)
 {
     LOG_FMT_ERR("API shutdown exception: %s", e.what());
     return false;
 }
start()
bool AbstractAPI::start (void) inherited
common implementation of API start procedure
Returns
true API started successfully
false if API did not start
Definition at line 16 of file AbstractAPI.cpp.
References AbstractAPI::apiThread, LOG_FMT_FTL, LOG_MSG_ERR, LOG_MSG_FTL, AbstractAPI::setRunFlag(), AbstractAPI::setupApi(), AbstractAPI::threadBody(), and AbstractAPI::validatorInitialized.
Referenced by Application::run().
 {
     if (!validatorInitialized)
     {
         LOG_MSG_ERR("unable to start API, JSON validator not initialized");
         return false;
     }
     if (!setupApi())
     {
         LOG_MSG_FTL("failed to setup API");
         return false;
     }
     try
     {
         setRunFlag(true);
         apiThread = new std::thread(threadBody, this);
     }
     catch (const std::exception &e)
     {
         setRunFlag(false);
         LOG_FMT_FTL("failed to allocate thread memory: %s", e.what());
         return false;
     }
     return true;
 }
stop()
void AbstractAPI::stop (void) inherited
stop API and deallocate resources
Definition at line 46 of file AbstractAPI.cpp.
References AbstractAPI::apiThread, AbstractAPI::setRunFlag(), and AbstractAPI::shutdownApi().
Referenced by Application::run().
 {
     setRunFlag(false);
     shutdownApi();
     if (apiThread != nullptr)
     {
         apiThread->join();
         delete apiThread;
         apiThread = nullptr;
     }
 }
Member Data Documentation
port
const uint16_t RestAPI::port private
Definition at line 65 of file RestAPI.hpp.
Referenced by setupApi().
resourceGet
std::shared_ptr<restbed::Resource> RestAPI::resourceGet private
Definition at line 68 of file RestAPI.hpp.
Referenced by setupApi().
resourcePost
std::shared_ptr<restbed::Resource> RestAPI::resourcePost private
Definition at line 67 of file RestAPI.hpp.
Referenced by setupApi().
service
restbed::Service RestAPI::service private
Definition at line 69 of file RestAPI.hpp.
Referenced by run(), setupApi(), and shutdownApi().
settings
std::shared_ptr<restbed::Settings> RestAPI::settings private
Definition at line 66 of file RestAPI.hpp.
Referenced by run(), and setupApi().
thisApi
RestAPI * RestAPI::thisApi static private
Definition at line 73 of file RestAPI.hpp.
Referenced by postHandler(), and RestAPI().
The documentation for this class was generated from the following files:
src/deviceMonitor/apis/RestAPI.hpp
src/deviceMonitor/apis/RestAPI.cpp